import {Model, ModelOrigin, ModelType} from '../utils/types';
import {chatTemplates} from '../utils/chat';
import {defaultCompletionParams} from '../utils/completionSettingsVersions';
import {Platform} from 'react-native';

export const MODEL_LIST_VERSION = 18;

const iosOnlyModels: Model[] = [];
const androidOnlyModels: Model[] = [];

const crossPlatformModels: Model[] = [

  // ════════════════════════════════════════════
  // 🪶 ULTRA LÉGERS — minRamGB: 2 (téléphones 3-4GB)
  // ════════════════════════════════════════════

  {
    id: 'TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF/tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf',
    author: 'TheBloke',
    repo: 'TinyLlama-1.1B-Chat-v1.0-GGUF',
    name: 'TinyLlama 1.1B Chat (Q4_K_M)',
    type: 'Llama',
    country: '🇺🇸',
    minRamGB: 2,
    capabilities: ['instructions', 'summarization'],
    size: 668000000,
    params: 1100000000,
    isDownloaded: false,
    downloadUrl: 'https://huggingface.co/TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF/resolve/main/tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf',
    hfUrl: 'https://huggingface.co/TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF',
    progress: 0,
    filename: 'tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf',
    isLocal: false,
    origin: ModelOrigin.PRESET,
    defaultChatTemplate: {...chatTemplates.llama3},
    chatTemplate: chatTemplates.llama3,
    defaultCompletionSettings: {...defaultCompletionParams, n_predict: 500, temperature: 0.7},
    completionSettings: {...defaultCompletionParams, n_predict: 500, temperature: 0.7},
    defaultStopWords: ['</s>'],
    stopWords: ['</s>'],
    hfModelFile: {
      rfilename: 'tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf',
      url: 'https://huggingface.co/TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF/resolve/main/tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf',
      size: 668000000,
      canFitInStorage: true,
    },
  },

  {
    id: 'bartowski/google_gemma-3-1b-it-GGUF/google_gemma-3-1b-it-Q4_K_M.gguf',
    author: 'bartowski',
    repo: 'google_gemma-3-1b-it-GGUF',
    name: 'Gemma 3 1B (Q4_K_M)',
    type: 'Gemma',
    country: '🇬🇧',
    minRamGB: 2,
    capabilities: ['instructions', 'summarization', 'multilingual'],
    size: 600000000,
    params: 1000000000,
    isDownloaded: false,
    downloadUrl: 'https://huggingface.co/bartowski/google_gemma-3-1b-it-GGUF/resolve/main/google_gemma-3-1b-it-Q4_K_M.gguf',
    hfUrl: 'https://huggingface.co/bartowski/google_gemma-3-1b-it-GGUF',
    progress: 0,
    filename: 'google_gemma-3-1b-it-Q4_K_M.gguf',
    isLocal: false,
    origin: ModelOrigin.PRESET,
    defaultChatTemplate: {...chatTemplates.gemmaIt},
    chatTemplate: chatTemplates.gemmaIt,
    defaultCompletionSettings: {...defaultCompletionParams, n_predict: 500, temperature: 0.7},
    completionSettings: {...defaultCompletionParams, n_predict: 500, temperature: 0.7},
    defaultStopWords: ['<end_of_turn>'],
    stopWords: ['<end_of_turn>'],
    hfModelFile: {
      rfilename: 'google_gemma-3-1b-it-Q4_K_M.gguf',
      url: 'https://huggingface.co/bartowski/google_gemma-3-1b-it-GGUF/resolve/main/google_gemma-3-1b-it-Q4_K_M.gguf',
      size: 600000000,
      canFitInStorage: true,
    },
  },

  {
    id: 'bartowski/SmolLM2-1.7B-Instruct-GGUF/SmolLM2-1.7B-Instruct-Q4_K_M.gguf',
    author: 'bartowski',
    repo: 'SmolLM2-1.7B-Instruct-GGUF',
    name: 'SmolLM2 1.7B (Q4_K_M)',
    type: 'SmolLM',
    country: '🇫🇷',
    minRamGB: 2,
    capabilities: ['instructions', 'summarization'],
    size: 1000000000,
    params: 1711376384,
    isDownloaded: false,
    downloadUrl: 'https://huggingface.co/bartowski/SmolLM2-1.7B-Instruct-GGUF/resolve/main/SmolLM2-1.7B-Instruct-Q4_K_M.gguf',
    hfUrl: 'https://huggingface.co/bartowski/SmolLM2-1.7B-Instruct-GGUF',
    progress: 0,
    filename: 'SmolLM2-1.7B-Instruct-Q4_K_M.gguf',
    isLocal: false,
    origin: ModelOrigin.PRESET,
    defaultChatTemplate: chatTemplates.smolLM,
    chatTemplate: chatTemplates.smolLM,
    defaultCompletionSettings: {...defaultCompletionParams, n_predict: 500, temperature: 0.7},
    completionSettings: {...defaultCompletionParams, n_predict: 500, temperature: 0.7},
    defaultStopWords: ['<|endoftext|>', '<|im_end|>'],
    stopWords: ['<|endoftext|>', '<|im_end|>'],
    supportsThinking: false,
    hfModelFile: {
      rfilename: 'SmolLM2-1.7B-Instruct-Q4_K_M.gguf',
      url: 'https://huggingface.co/bartowski/SmolLM2-1.7B-Instruct-GGUF/resolve/main/SmolLM2-1.7B-Instruct-Q4_K_M.gguf',
      size: 1000000000,
      canFitInStorage: true,
    },
  },

  {
    id: 'bartowski/Qwen_Qwen3-1.7B-GGUF/Qwen_Qwen3-1.7B-Q4_K_M.gguf',
    author: 'bartowski',
    repo: 'Qwen_Qwen3-1.7B-GGUF',
    name: 'Qwen3 1.7B (Q4_K_M)',
    type: 'Qwen',
    country: '🇨🇳',
    minRamGB: 2,
    capabilities: ['instructions', 'reasoning', 'multilingual'],
    size: 1100000000,
    params: 1777088000,
    isDownloaded: false,
    downloadUrl: 'https://huggingface.co/bartowski/Qwen_Qwen3-1.7B-GGUF/resolve/main/Qwen_Qwen3-1.7B-Q4_K_M.gguf',
    hfUrl: 'https://huggingface.co/bartowski/Qwen_Qwen3-1.7B-GGUF',
    progress: 0,
    filename: 'Qwen_Qwen3-1.7B-Q4_K_M.gguf',
    isLocal: false,
    origin: ModelOrigin.PRESET,
    defaultChatTemplate: {...chatTemplates.qwen25},
    chatTemplate: chatTemplates.qwen25,
    defaultCompletionSettings: {...defaultCompletionParams, n_predict: 500, temperature: 0.6},
    completionSettings: {...defaultCompletionParams, n_predict: 500, temperature: 0.6},
    defaultStopWords: ['<|im_end|>'],
    stopWords: ['<|im_end|>'],
    supportsThinking: true,
    hfModelFile: {
      rfilename: 'Qwen_Qwen3-1.7B-Q4_K_M.gguf',
      url: 'https://huggingface.co/bartowski/Qwen_Qwen3-1.7B-GGUF/resolve/main/Qwen_Qwen3-1.7B-Q4_K_M.gguf',
      size: 1100000000,
      canFitInStorage: true,
    },
  },

  // ════════════════════════════════════════════
  // ⚖️ LÉGERS — minRamGB: 4 (téléphones 4-6GB)
  // ════════════════════════════════════════════

  {
    id: 'bartowski/google_gemma-3-4b-it-GGUF/google_gemma-3-4b-it-Q4_K_M.gguf',
    author: 'bartowski',
    repo: 'google_gemma-3-4b-it-GGUF',
    name: 'Gemma 3 4B (Q4_K_M)',
    type: 'Gemma',
    country: '🇬🇧',
    minRamGB: 4,
    capabilities: ['instructions', 'summarization', 'reasoning', 'multilingual', 'creativity'],
    size: 2600000000,
    params: 4000000000,
    isDownloaded: false,
    downloadUrl: 'https://huggingface.co/bartowski/google_gemma-3-4b-it-GGUF/resolve/main/google_gemma-3-4b-it-Q4_K_M.gguf',
    hfUrl: 'https://huggingface.co/bartowski/google_gemma-3-4b-it-GGUF',
    progress: 0,
    filename: 'google_gemma-3-4b-it-Q4_K_M.gguf',
    isLocal: false,
    origin: ModelOrigin.PRESET,
    defaultChatTemplate: {...chatTemplates.gemmaIt},
    chatTemplate: chatTemplates.gemmaIt,
    defaultCompletionSettings: {...defaultCompletionParams, n_predict: 800, temperature: 0.7},
    completionSettings: {...defaultCompletionParams, n_predict: 800, temperature: 0.7},
    defaultStopWords: ['<end_of_turn>'],
    stopWords: ['<end_of_turn>'],
    hfModelFile: {
      rfilename: 'google_gemma-3-4b-it-Q4_K_M.gguf',
      url: 'https://huggingface.co/bartowski/google_gemma-3-4b-it-GGUF/resolve/main/google_gemma-3-4b-it-Q4_K_M.gguf',
      size: 2600000000,
      canFitInStorage: true,
    },
  },

  {
    id: 'bartowski/Qwen_Qwen3-4B-GGUF/Qwen_Qwen3-4B-Q4_K_M.gguf',
    author: 'bartowski',
    repo: 'Qwen_Qwen3-4B-GGUF',
    name: 'Qwen3 4B (Q4_K_M)',
    type: 'Qwen',
    country: '🇨🇳',
    minRamGB: 4,
    capabilities: ['instructions', 'reasoning', 'code', 'multilingual'],
    size: 2600000000,
    params: 4000000000,
    isDownloaded: false,
    downloadUrl: 'https://huggingface.co/bartowski/Qwen_Qwen3-4B-GGUF/resolve/main/Qwen_Qwen3-4B-Q4_K_M.gguf',
    hfUrl: 'https://huggingface.co/bartowski/Qwen_Qwen3-4B-GGUF',
    progress: 0,
    filename: 'Qwen_Qwen3-4B-Q4_K_M.gguf',
    isLocal: false,
    origin: ModelOrigin.PRESET,
    defaultChatTemplate: {...chatTemplates.qwen25},
    chatTemplate: chatTemplates.qwen25,
    defaultCompletionSettings: {...defaultCompletionParams, n_predict: 800, temperature: 0.6},
    completionSettings: {...defaultCompletionParams, n_predict: 800, temperature: 0.6},
    defaultStopWords: ['<|im_end|>'],
    stopWords: ['<|im_end|>'],
    supportsThinking: true,
    hfModelFile: {
      rfilename: 'Qwen_Qwen3-4B-Q4_K_M.gguf',
      url: 'https://huggingface.co/bartowski/Qwen_Qwen3-4B-GGUF/resolve/main/Qwen_Qwen3-4B-Q4_K_M.gguf',
      size: 2600000000,
      canFitInStorage: true,
    },
  },

  // ════════════════════════════════════════════
  // 💪 PUISSANTS — minRamGB: 5-6 (téléphones 6-8GB)
  // ════════════════════════════════════════════

  {
    id: 'bartowski/Mistral-7B-Instruct-v0.3-GGUF/Mistral-7B-Instruct-v0.3-Q4_K_M.gguf',
    author: 'bartowski',
    repo: 'Mistral-7B-Instruct-v0.3-GGUF',
    name: 'Mistral 7B Instruct v0.3 (Q4_K_M)',
    type: 'Mistral',
    country: '🇫🇷',
    minRamGB: 8,
    capabilities: ['instructions', 'summarization', 'reasoning', 'multilingual', 'rewriting'],
    size: 4370000000,
    params: 7242000000,
    isDownloaded: false,
    downloadUrl: 'https://huggingface.co/bartowski/Mistral-7B-Instruct-v0.3-GGUF/resolve/main/Mistral-7B-Instruct-v0.3-Q4_K_M.gguf',
    hfUrl: 'https://huggingface.co/bartowski/Mistral-7B-Instruct-v0.3-GGUF',
    progress: 0,
    filename: 'Mistral-7B-Instruct-v0.3-Q4_K_M.gguf',
    isLocal: false,
    origin: ModelOrigin.PRESET,
    defaultChatTemplate: {...chatTemplates.default},
    chatTemplate: chatTemplates.default,
    defaultCompletionSettings: {...defaultCompletionParams, n_predict: 1000, temperature: 0.7},
    completionSettings: {...defaultCompletionParams, n_predict: 1000, temperature: 0.7},
    defaultStopWords: ['</s>', '[INST]', '[/INST]'],
    stopWords: ['</s>', '[INST]', '[/INST]'],
    hfModelFile: {
      rfilename: 'Mistral-7B-Instruct-v0.3-Q4_K_M.gguf',
      url: 'https://huggingface.co/bartowski/Mistral-7B-Instruct-v0.3-GGUF/resolve/main/Mistral-7B-Instruct-v0.3-Q4_K_M.gguf',
      size: 4370000000,
      canFitInStorage: true,
    },
  },

  {
    id: 'bartowski/mistralai_Ministral-3-8B-Instruct-2512-GGUF/mistralai_Ministral-3-8B-Instruct-2512-Q4_K_M.gguf',
    author: 'bartowski',
    repo: 'mistralai_Ministral-3-8B-Instruct-2512-GGUF',
    name: 'Ministral 3 8B Instruct (Q4_K_M)',
    type: 'Mistral',
    country: '🇫🇷',
    minRamGB: 8,
    capabilities: ['instructions', 'summarization', 'reasoning', 'multilingual', 'rewriting'],
    size: 4920000000,
    params: 8000000000,
    isDownloaded: false,
    downloadUrl: 'https://huggingface.co/bartowski/mistralai_Ministral-3-8B-Instruct-2512-GGUF/resolve/main/mistralai_Ministral-3-8B-Instruct-2512-Q4_K_M.gguf',
    hfUrl: 'https://huggingface.co/bartowski/mistralai_Ministral-3-8B-Instruct-2512-GGUF',
    progress: 0,
    filename: 'mistralai_Ministral-3-8B-Instruct-2512-Q4_K_M.gguf',
    isLocal: false,
    origin: ModelOrigin.PRESET,
    defaultChatTemplate: {...chatTemplates.default},
    chatTemplate: chatTemplates.default,
    defaultCompletionSettings: {...defaultCompletionParams, n_predict: 1000, temperature: 0.7},
    completionSettings: {...defaultCompletionParams, n_predict: 1000, temperature: 0.7},
    defaultStopWords: ['</s>', '[INST]', '[/INST]'],
    stopWords: ['</s>', '[INST]', '[/INST]'],
    hfModelFile: {
      rfilename: 'mistralai_Ministral-3-8B-Instruct-2512-Q4_K_M.gguf',
      url: 'https://huggingface.co/bartowski/mistralai_Ministral-3-8B-Instruct-2512-GGUF/resolve/main/mistralai_Ministral-3-8B-Instruct-2512-Q4_K_M.gguf',
      size: 4920000000,
      canFitInStorage: true,
    },
  },

  {
    id: 'bartowski/Meta-Llama-3.1-8B-Instruct-GGUF/Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf',
    author: 'bartowski',
    repo: 'Meta-Llama-3.1-8B-Instruct-GGUF',
    name: 'Llama 3.1 8B Instruct (Q4_K_M)',
    type: 'Llama',
    country: '🇺🇸',
    minRamGB: 6,
    capabilities: ['instructions', 'summarization', 'reasoning', 'rewriting', 'multilingual'],
    size: 4920000000,
    params: 8030000000,
    isDownloaded: false,
    downloadUrl: 'https://huggingface.co/bartowski/Meta-Llama-3.1-8B-Instruct-GGUF/resolve/main/Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf',
    hfUrl: 'https://huggingface.co/bartowski/Meta-Llama-3.1-8B-Instruct-GGUF',
    progress: 0,
    filename: 'Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf',
    isLocal: false,
    origin: ModelOrigin.PRESET,
    defaultChatTemplate: {...chatTemplates.llama3},
    chatTemplate: chatTemplates.llama3,
    defaultCompletionSettings: {...defaultCompletionParams, n_predict: 1000, temperature: 0.6},
    completionSettings: {...defaultCompletionParams, n_predict: 1000, temperature: 0.6},
    defaultStopWords: ['<|eot_id|>'],
    stopWords: ['<|eot_id|>'],
    hfModelFile: {
      rfilename: 'Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf',
      url: 'https://huggingface.co/bartowski/Meta-Llama-3.1-8B-Instruct-GGUF/resolve/main/Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf',
      size: 4920000000,
      canFitInStorage: true,
    },
  },

  {
    id: 'bartowski/Qwen_Qwen3-8B-GGUF/Qwen_Qwen3-8B-Q4_K_M.gguf',
    author: 'bartowski',
    repo: 'Qwen_Qwen3-8B-GGUF',
    name: 'Qwen3 8B (Q4_K_M)',
    type: 'Qwen',
    country: '🇨🇳',
    minRamGB: 6,
    capabilities: ['instructions', 'reasoning', 'code', 'math', 'multilingual'],
    size: 5200000000,
    params: 8000000000,
    isDownloaded: false,
    downloadUrl: 'https://huggingface.co/bartowski/Qwen_Qwen3-8B-GGUF/resolve/main/Qwen_Qwen3-8B-Q4_K_M.gguf',
    hfUrl: 'https://huggingface.co/bartowski/Qwen_Qwen3-8B-GGUF',
    progress: 0,
    filename: 'Qwen_Qwen3-8B-Q4_K_M.gguf',
    isLocal: false,
    origin: ModelOrigin.PRESET,
    defaultChatTemplate: {...chatTemplates.qwen25},
    chatTemplate: chatTemplates.qwen25,
    defaultCompletionSettings: {...defaultCompletionParams, n_predict: 1000, temperature: 0.6},
    completionSettings: {...defaultCompletionParams, n_predict: 1000, temperature: 0.6},
    defaultStopWords: ['<|im_end|>'],
    stopWords: ['<|im_end|>'],
    supportsThinking: true,
    hfModelFile: {
      rfilename: 'Qwen_Qwen3-8B-Q4_K_M.gguf',
      url: 'https://huggingface.co/bartowski/Qwen_Qwen3-8B-GGUF/resolve/main/Qwen_Qwen3-8B-Q4_K_M.gguf',
      size: 5200000000,
      canFitInStorage: true,
    },
  },

  // ════════════════════════════════════════════
  // 🚀 HAUT DE GAMME — minRamGB: 8-10 (téléphones 10-12GB)
  // ════════════════════════════════════════════

  {
    id: 'bartowski/Mistral-Nemo-Instruct-2407-GGUF/Mistral-Nemo-Instruct-2407-Q4_K_M.gguf',
    author: 'bartowski',
    repo: 'Mistral-Nemo-Instruct-2407-GGUF',
    name: 'Mistral Nemo 12B (Q4_K_M)',
    type: 'Mistral',
    country: '🇫🇷',
    minRamGB: 8,
    capabilities: ['instructions', 'summarization', 'reasoning', 'multilingual', 'rewriting', 'creativity'],
    size: 7700000000,
    params: 12248000000,
    isDownloaded: false,
    downloadUrl: 'https://huggingface.co/bartowski/Mistral-Nemo-Instruct-2407-GGUF/resolve/main/Mistral-Nemo-Instruct-2407-Q4_K_M.gguf',
    hfUrl: 'https://huggingface.co/bartowski/Mistral-Nemo-Instruct-2407-GGUF',
    progress: 0,
    filename: 'Mistral-Nemo-Instruct-2407-Q4_K_M.gguf',
    isLocal: false,
    origin: ModelOrigin.PRESET,
    defaultChatTemplate: {...chatTemplates.default},
    chatTemplate: chatTemplates.default,
    defaultCompletionSettings: {...defaultCompletionParams, n_predict: 1500, temperature: 0.7},
    completionSettings: {...defaultCompletionParams, n_predict: 1500, temperature: 0.7},
    defaultStopWords: ['</s>', '[INST]', '[/INST]'],
    stopWords: ['</s>', '[INST]', '[/INST]'],
    hfModelFile: {
      rfilename: 'Mistral-Nemo-Instruct-2407-Q4_K_M.gguf',
      url: 'https://huggingface.co/bartowski/Mistral-Nemo-Instruct-2407-GGUF/resolve/main/Mistral-Nemo-Instruct-2407-Q4_K_M.gguf',
      size: 7700000000,
      canFitInStorage: true,
    },
  },

  {
    id: 'bartowski/google_gemma-3-12b-it-GGUF/google_gemma-3-12b-it-Q4_K_M.gguf',
    author: 'bartowski',
    repo: 'google_gemma-3-12b-it-GGUF',
    name: 'Gemma 3 12B (Q4_K_M)',
    type: 'Gemma',
    country: '🇬🇧',
    minRamGB: 8,
    capabilities: ['instructions', 'summarization', 'reasoning', 'multilingual', 'creativity'],
    size: 8100000000,
    params: 12000000000,
    isDownloaded: false,
    downloadUrl: 'https://huggingface.co/bartowski/google_gemma-3-12b-it-GGUF/resolve/main/google_gemma-3-12b-it-Q4_K_M.gguf',
    hfUrl: 'https://huggingface.co/bartowski/google_gemma-3-12b-it-GGUF',
    progress: 0,
    filename: 'google_gemma-3-12b-it-Q4_K_M.gguf',
    isLocal: false,
    origin: ModelOrigin.PRESET,
    defaultChatTemplate: {...chatTemplates.gemmaIt},
    chatTemplate: chatTemplates.gemmaIt,
    defaultCompletionSettings: {...defaultCompletionParams, n_predict: 1500, temperature: 0.7},
    completionSettings: {...defaultCompletionParams, n_predict: 1500, temperature: 0.7},
    defaultStopWords: ['<end_of_turn>'],
    stopWords: ['<end_of_turn>'],
    hfModelFile: {
      rfilename: 'google_gemma-3-12b-it-Q4_K_M.gguf',
      url: 'https://huggingface.co/bartowski/google_gemma-3-12b-it-GGUF/resolve/main/google_gemma-3-12b-it-Q4_K_M.gguf',
      size: 8100000000,
      canFitInStorage: true,
    },
  },

  {
    id: 'bartowski/Qwen_Qwen3-14B-GGUF/Qwen_Qwen3-14B-Q4_K_M.gguf',
    author: 'bartowski',
    repo: 'Qwen_Qwen3-14B-GGUF',
    name: 'Qwen3 14B (Q4_K_M)',
    type: 'Qwen',
    country: '🇨🇳',
    minRamGB: 10,
    capabilities: ['instructions', 'reasoning', 'code', 'math', 'multilingual'],
    size: 9200000000,
    params: 14000000000,
    isDownloaded: false,
    downloadUrl: 'https://huggingface.co/bartowski/Qwen_Qwen3-14B-GGUF/resolve/main/Qwen_Qwen3-14B-Q4_K_M.gguf',
    hfUrl: 'https://huggingface.co/bartowski/Qwen_Qwen3-14B-GGUF',
    progress: 0,
    filename: 'Qwen_Qwen3-14B-Q4_K_M.gguf',
    isLocal: false,
    origin: ModelOrigin.PRESET,
    defaultChatTemplate: {...chatTemplates.qwen25},
    chatTemplate: chatTemplates.qwen25,
    defaultCompletionSettings: {...defaultCompletionParams, n_predict: 1500, temperature: 0.6},
    completionSettings: {...defaultCompletionParams, n_predict: 1500, temperature: 0.6},
    defaultStopWords: ['<|im_end|>'],
    stopWords: ['<|im_end|>'],
    supportsThinking: true,
    hfModelFile: {
      rfilename: 'Qwen_Qwen3-14B-Q4_K_M.gguf',
      url: 'https://huggingface.co/bartowski/Qwen_Qwen3-14B-GGUF/resolve/main/Qwen_Qwen3-14B-Q4_K_M.gguf',
      size: 9200000000,
      canFitInStorage: true,
    },
  },

  {
    id: 'bartowski/Mistral-Small-3.1-24B-Instruct-2503-GGUF/Mistral-Small-3.1-24B-Instruct-2503-Q4_K_M.gguf',
    author: 'bartowski',
    repo: 'Mistral-Small-3.1-24B-Instruct-2503-GGUF',
    name: 'Mistral Small 24B (Q4_K_M)',
    type: 'Mistral',
    country: '🇫🇷',
    minRamGB: 14,
    capabilities: ['instructions', 'summarization', 'reasoning', 'multilingual', 'rewriting', 'creativity', 'code'],
    size: 14800000000,
    params: 24000000000,
    isDownloaded: false,
    downloadUrl: 'https://huggingface.co/bartowski/Mistral-Small-3.1-24B-Instruct-2503-GGUF/resolve/main/Mistral-Small-3.1-24B-Instruct-2503-Q4_K_M.gguf',
    hfUrl: 'https://huggingface.co/bartowski/Mistral-Small-3.1-24B-Instruct-2503-GGUF',
    progress: 0,
    filename: 'Mistral-Small-3.1-24B-Instruct-2503-Q4_K_M.gguf',
    isLocal: false,
    origin: ModelOrigin.PRESET,
    defaultChatTemplate: {...chatTemplates.default},
    chatTemplate: chatTemplates.default,
    defaultCompletionSettings: {...defaultCompletionParams, n_predict: 2000, temperature: 0.7},
    completionSettings: {...defaultCompletionParams, n_predict: 2000, temperature: 0.7},
    defaultStopWords: ['</s>', '[INST]', '[/INST]'],
    stopWords: ['</s>', '[INST]', '[/INST]'],
    hfModelFile: {
      rfilename: 'Mistral-Small-3.1-24B-Instruct-2503-Q4_K_M.gguf',
      url: 'https://huggingface.co/bartowski/Mistral-Small-3.1-24B-Instruct-2503-GGUF/resolve/main/Mistral-Small-3.1-24B-Instruct-2503-Q4_K_M.gguf',
      size: 14800000000,
      canFitInStorage: true,
    },
  },

  // ════════════════════════════════════════════
  // 👁️ VISION — SmolVLM (tous appareils 2GB+)
  // ════════════════════════════════════════════

  {
    id: 'ggml-org/SmolVLM-500M-Instruct-GGUF/SmolVLM-500M-Instruct-Q8_0.gguf',
    author: 'ggml-org',
    repo: 'SmolVLM-500M-Instruct-GGUF',
    name: 'SmolVLM2 500M Vision (Q8_0)',
    type: 'SmolVLM',
    country: '🇫🇷',
    minRamGB: 2,
    capabilities: ['vision'],
    visionEnabled: true,
    size: 436806912,
    params: 409252800,
    isDownloaded: false,
    downloadUrl: 'https://huggingface.co/ggml-org/SmolVLM-500M-Instruct-GGUF/resolve/main/SmolVLM-500M-Instruct-Q8_0.gguf',
    hfUrl: 'https://huggingface.co/ggml-org/SmolVLM-500M-Instruct-GGUF',
    progress: 0,
    filename: 'SmolVLM-500M-Instruct-Q8_0.gguf',
    isLocal: false,
    origin: ModelOrigin.PRESET,
    modelType: ModelType.VISION,
    defaultChatTemplate: chatTemplates.smolVLM,
    chatTemplate: chatTemplates.smolVLM,
    defaultCompletionSettings: {...defaultCompletionParams, n_predict: 500, temperature: 0.7},
    completionSettings: {...defaultCompletionParams, n_predict: 500, temperature: 0.7},
    defaultStopWords: ['<|endoftext|>', '<|im_end|>', '<end_of_utterance>'],
    stopWords: ['<|endoftext|>', '<|im_end|>', '<end_of_utterance>'],
    hfModelFile: {
      rfilename: 'SmolVLM-500M-Instruct-Q8_0.gguf',
      url: 'https://huggingface.co/ggml-org/SmolVLM-500M-Instruct-GGUF/resolve/main/SmolVLM-500M-Instruct-Q8_0.gguf',
      size: 436806912,
      canFitInStorage: true,
    },
    supportsMultimodal: true,
    compatibleProjectionModels: [
      'ggml-org/SmolVLM-500M-Instruct-GGUF/mmproj-SmolVLM-500M-Instruct-Q8_0.gguf',
    ],
    defaultProjectionModel: 'ggml-org/SmolVLM-500M-Instruct-GGUF/mmproj-SmolVLM-500M-Instruct-Q8_0.gguf',
  },
  {
    id: 'ggml-org/SmolVLM-500M-Instruct-GGUF/mmproj-SmolVLM-500M-Instruct-Q8_0.gguf',
    author: 'ggml-org',
    repo: 'SmolVLM-500M-Instruct-GGUF',
    name: 'mmproj-SmolVLM2-500M (Q8_0)',
    type: 'SmolVLM',
    country: '🇫🇷',
    minRamGB: 2,
    capabilities: [],
    size: 108783360,
    params: 409252800,
    isDownloaded: false,
    downloadUrl: 'https://huggingface.co/ggml-org/SmolVLM-500M-Instruct-GGUF/resolve/main/mmproj-SmolVLM-500M-Instruct-Q8_0.gguf',
    hfUrl: 'https://huggingface.co/ggml-org/SmolVLM-500M-Instruct-GGUF',
    progress: 0,
    filename: 'mmproj-SmolVLM-500M-Instruct-Q8_0.gguf',
    isLocal: false,
    origin: ModelOrigin.PRESET,
    modelType: ModelType.PROJECTION,
    defaultChatTemplate: chatTemplates.smolVLM,
    chatTemplate: chatTemplates.smolVLM,
    defaultCompletionSettings: {...defaultCompletionParams, n_predict: 500, temperature: 0.7},
    completionSettings: {...defaultCompletionParams, n_predict: 500, temperature: 0.7},
    defaultStopWords: ['<|endoftext|>', '<|im_end|>', '<end_of_utterance>'],
    stopWords: ['<|endoftext|>', '<|im_end|>', '<end_of_utterance>'],
    hfModelFile: {
      rfilename: 'mmproj-SmolVLM-500M-Instruct-Q8_0.gguf',
      url: 'https://huggingface.co/ggml-org/SmolVLM-500M-Instruct-GGUF/resolve/main/mmproj-SmolVLM-500M-Instruct-Q8_0.gguf',
      size: 108783360,
      canFitInStorage: true,
    },
  },
];

export const defaultModels =
  Platform.OS === 'android'
    ? [...androidOnlyModels, ...crossPlatformModels]
    : [...iosOnlyModels, ...crossPlatformModels];
